// Code generated by Kitex v0.4.4. DO NOT EDIT.

package videoservice

import (
	"context"
	demovideo "douyin/kitex_gen/demovideo"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetFeedList(ctx context.Context, req *demovideo.DouyinFeedRequest, callOptions ...callopt.Option) (r *demovideo.DouyinFeedResponse, err error)
	FavoriteAction(ctx context.Context, req *demovideo.DouyinFavoriteActionRequest, callOptions ...callopt.Option) (r *demovideo.DouyinFavoriteActionResponse, err error)
	CommentAction(ctx context.Context, req *demovideo.DouyinCommentActionRequest, callOptions ...callopt.Option) (r *demovideo.DouyinCommentActionResponse, err error)
	GetCommentList(ctx context.Context, req *demovideo.DouyinCommentListRequest, callOptions ...callopt.Option) (r *demovideo.DouyinCommentListResponse, err error)
	CreateVideo(ctx context.Context, req *demovideo.DouyinCreateVideoRequest, callOptions ...callopt.Option) (r *demovideo.DouyinCreateVideoResponse, err error)
	MutilGetVideo(ctx context.Context, req *demovideo.DouyinQueryVideoResponse, callOptions ...callopt.Option) (r *demovideo.DouyinQueryVideoResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) GetFeedList(ctx context.Context, req *demovideo.DouyinFeedRequest, callOptions ...callopt.Option) (r *demovideo.DouyinFeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFeedList(ctx, req)
}

func (p *kVideoServiceClient) FavoriteAction(ctx context.Context, req *demovideo.DouyinFavoriteActionRequest, callOptions ...callopt.Option) (r *demovideo.DouyinFavoriteActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FavoriteAction(ctx, req)
}

func (p *kVideoServiceClient) CommentAction(ctx context.Context, req *demovideo.DouyinCommentActionRequest, callOptions ...callopt.Option) (r *demovideo.DouyinCommentActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentAction(ctx, req)
}

func (p *kVideoServiceClient) GetCommentList(ctx context.Context, req *demovideo.DouyinCommentListRequest, callOptions ...callopt.Option) (r *demovideo.DouyinCommentListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCommentList(ctx, req)
}

func (p *kVideoServiceClient) CreateVideo(ctx context.Context, req *demovideo.DouyinCreateVideoRequest, callOptions ...callopt.Option) (r *demovideo.DouyinCreateVideoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateVideo(ctx, req)
}

func (p *kVideoServiceClient) MutilGetVideo(ctx context.Context, req *demovideo.DouyinQueryVideoResponse, callOptions ...callopt.Option) (r *demovideo.DouyinQueryVideoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MutilGetVideo(ctx, req)
}
