// Code generated by Kitex v0.4.4. DO NOT EDIT.

package userservice

import (
	"context"
	demouser "douyin/kitex_gen/demouser"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UserRegister(ctx context.Context, req *demouser.DouyinUserRegisterRequest, callOptions ...callopt.Option) (r *demouser.DouyinUserRegisterResponse, err error)
	UserLogin(ctx context.Context, req *demouser.DouyinUserLoginRequest, callOptions ...callopt.Option) (r *demouser.DouyinUserLoginResponse, err error)
	CheckUserToken(ctx context.Context, req *demouser.DouyinUserCheckRequest, callOptions ...callopt.Option) (r *demouser.DouyinUserCheckResponse, err error)
	GetUserInfo(ctx context.Context, req *demouser.DouyinUserRequest, callOptions ...callopt.Option) (r *demouser.DouyinUserResponse, err error)
	PublishAction(ctx context.Context, req *demouser.DouyinPublishActionRequest, callOptions ...callopt.Option) (r *demouser.DouyinPublishActionResponse, err error)
	GetPublishList(ctx context.Context, req *demouser.DouyinPublishListRequest, callOptions ...callopt.Option) (r *demouser.DouyinPublishListResponse, err error)
	GetFavoriteList(ctx context.Context, req *demouser.DouyinFavoriteListRequest, callOptions ...callopt.Option) (r *demouser.DouyinFavoriteListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) UserRegister(ctx context.Context, req *demouser.DouyinUserRegisterRequest, callOptions ...callopt.Option) (r *demouser.DouyinUserRegisterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserRegister(ctx, req)
}

func (p *kUserServiceClient) UserLogin(ctx context.Context, req *demouser.DouyinUserLoginRequest, callOptions ...callopt.Option) (r *demouser.DouyinUserLoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserLogin(ctx, req)
}

func (p *kUserServiceClient) CheckUserToken(ctx context.Context, req *demouser.DouyinUserCheckRequest, callOptions ...callopt.Option) (r *demouser.DouyinUserCheckResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckUserToken(ctx, req)
}

func (p *kUserServiceClient) GetUserInfo(ctx context.Context, req *demouser.DouyinUserRequest, callOptions ...callopt.Option) (r *demouser.DouyinUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserInfo(ctx, req)
}

func (p *kUserServiceClient) PublishAction(ctx context.Context, req *demouser.DouyinPublishActionRequest, callOptions ...callopt.Option) (r *demouser.DouyinPublishActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishAction(ctx, req)
}

func (p *kUserServiceClient) GetPublishList(ctx context.Context, req *demouser.DouyinPublishListRequest, callOptions ...callopt.Option) (r *demouser.DouyinPublishListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPublishList(ctx, req)
}

func (p *kUserServiceClient) GetFavoriteList(ctx context.Context, req *demouser.DouyinFavoriteListRequest, callOptions ...callopt.Option) (r *demouser.DouyinFavoriteListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFavoriteList(ctx, req)
}
